# Generated by Django 3.1.3 on 2020-11-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_order_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
